# Generated by Django 5.0.1 on 2024-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_replied',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
