# Generated by Django 5.0.1 on 2024-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage_message_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message_replied',
            field=models.BooleanField(default=False),
        ),
    ]
